# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipelineConnection'
    subscriptionId: '07d5ccde-d400-4dd1-8539-4b00c715ba6d'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-farminvest'
    location: 'South Africa North'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/bennsid/AzureRmPipeline-repo/main/create_web_app/azuredeploy.json?token=GHSAT0AAAAAACD2HCJLYAXBTYHFNLIYZZNCZEHJRDQ'
    overrideParameters: '-projectName FarmInvest'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'